// Datos de la empresa
export const COMPANY_DATA = {
  name: "Autotron",
  legalName: "AUTOTRON SPA",
  rut: "76.407.685-0",
  address: "Av. Pedro Aguirre Cerda 1273, Valdivia, Región de Los Ríos, Chile",
  phone: "+56 9 9689 0273",
  email: "contacto@autotron.cl",
  website: "https://autotron.cl",
  foundationDate: "3 de marzo de 2015",
  companyType: "Sociedad por Acciones (SpA)",
  socialMedia: {
    facebook: "https://facebook.com/autotron",
    instagram: "https://instagram.com/autotron.cl",
    twitter: "https://twitter.com/autotron",
  },
}

// Marcas de vehículos
export const CAR_BRANDS = [
  { id: 1, name: "Chevrolet", logo: "/placeholder.svg?height=100&width=200" },
  { id: 2, name: "Mitsubishi", logo: "/placeholder.svg?height=100&width=200" },
  { id: 3, name: "Subaru", logo: "/placeholder.svg?height=100&width=200" },
  { id: 4, name: "Nissan", logo: "/placeholder.svg?height=100&width=200" },
  { id: 5, name: "Peugeot", logo: "/placeholder.svg?height=100&width=200" },
  { id: 6, name: "Honda", logo: "/placeholder.svg?height=100&width=200" },
  { id: 7, name: "Mazda", logo: "/placeholder.svg?height=100&width=200" },
  { id: 8, name: "Hyundai", logo: "/placeholder.svg?height=100&width=200" },
  { id: 9, name: "Toyota", logo: "/placeholder.svg?height=100&width=200" },
  { id: 10, name: "Ford", logo: "/placeholder.svg?height=100&width=200" },
]

// Datos de ejemplo para vehículos
export const VEHICLES_DATA = [
  {
    id: 1,
    brand: "Subaru",
    model: "New WRX",
    year: 2017,
    price: 20400000,
    type: "Usado",
    transmission: "Automática",
    fuel: "Gasolina",
    image: "/placeholder.svg?height=600&width=800",
    mileage: 45000,
    engine: "2.0L Turbo",
    power: "268 HP",
    acceleration: "5.5s (0-100 km/h)",
    topSpeed: "240 km/h",
    features: ["Tracción AWD", "Asientos deportivos", "Pantalla táctil", "Cámara de retroceso"],
  },
  {
    id: 2,
    brand: "Nissan",
    model: "Sentra",
    year: 2018,
    price: 8500000,
    type: "Usado",
    transmission: "Automática",
    fuel: "Gasolina",
    image: "/placeholder.svg?height=600&width=800",
    mileage: 62000,
    engine: "1.8L 4-Cilindros",
    power: "130 HP",
    acceleration: "9.8s (0-100 km/h)",
    topSpeed: "190 km/h",
    features: ["Bluetooth", "Aire acondicionado", "Airbags", "Control de crucero"],
  },
  {
    id: 3,
    brand: "Mitsubishi",
    model: "L200",
    year: 2018,
    price: 11500000,
    type: "Usado",
    transmission: "Manual",
    fuel: "Diésel",
    image: "/placeholder.svg?height=600&width=800",
    mileage: 85000,
    engine: "2.4L Turbo Diésel",
    power: "178 HP",
    acceleration: "10.5s (0-100 km/h)",
    topSpeed: "180 km/h",
    features: ["Tracción 4x4", "Capacidad de carga 1 ton", "Enganche", "Barra antivuelco"],
  },
  {
    id: 4,
    brand: "Chevrolet",
    model: "Captiva",
    year: 2016,
    price: 9800000,
    type: "Usado",
    transmission: "Automática",
    fuel: "Gasolina",
    image: "/placeholder.svg?height=600&width=800",
    mileage: 78000,
    engine: "2.4L 4-Cilindros",
    power: "167 HP",
    acceleration: "10.2s (0-100 km/h)",
    topSpeed: "190 km/h",
    features: ["7 plazas", "Cámara de retroceso", "Sensores de estacionamiento", "Climatizador"],
  },
  {
    id: 5,
    brand: "Toyota",
    model: "RAV4",
    year: 2019,
    price: 15900000,
    type: "Usado",
    transmission: "Automática",
    fuel: "Gasolina",
    image: "/placeholder.svg?height=600&width=800",
    mileage: 42000,
    engine: "2.5L 4-Cilindros",
    power: "176 HP",
    acceleration: "8.4s (0-100 km/h)",
    topSpeed: "200 km/h",
    features: ["Tracción AWD", "Apple CarPlay", "Techo panorámico", "Asientos calefactados"],
  },
  {
    id: 6,
    brand: "Honda",
    model: "Civic",
    year: 2020,
    price: 12500000,
    type: "Usado",
    transmission: "Automática",
    fuel: "Gasolina",
    image: "/placeholder.svg?height=600&width=800",
    mileage: 35000,
    engine: "1.5L Turbo",
    power: "174 HP",
    acceleration: "7.5s (0-100 km/h)",
    topSpeed: "210 km/h",
    features: ['Pantalla táctil 9"', "CarPlay inalámbrico", "Cámara de retroceso", "Sensores"],
  },
]

// Opciones para filtros
export const FILTER_OPTIONS = {
  brands: [
    "Todos",
    "Chevrolet",
    "Mitsubishi",
    "Subaru",
    "Nissan",
    "Peugeot",
    "Honda",
    "Mazda",
    "Hyundai",
    "Toyota",
    "Ford",
  ],
  types: ["Todos", "Nuevo", "Usado"],
  transmissions: ["Todos", "Automática", "Manual"],
  fuels: ["Todos", "Gasolina", "Diésel", "Híbrido", "Híbrido Enchufable", "Eléctrico"],
}

// Testimonios
export const TESTIMONIALS = [
  {
    id: 1,
    name: "Carlos Mendoza",
    role: "Empresario",
    quote:
      "Excelente servicio y atención. El proceso de compra fue rápido y transparente. Mi nuevo Subaru superó todas mis expectativas.",
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 2,
    name: "María Fernández",
    role: "Ingeniera",
    quote:
      "La experiencia de compra fue excepcional. El asesor me ayudó a encontrar el vehículo perfecto para mis necesidades y presupuesto.",
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 3,
    name: "Roberto Sánchez",
    role: "Médico",
    quote:
      "El servicio de lavado es de primera calidad. Rápidos, eficientes y con precios justos. Recomiendo totalmente Autotron.",
    rating: 4,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 4,
    name: "Ana Martínez",
    role: "Profesora",
    quote:
      "Alquilé un vehículo para mis vacaciones y fue una experiencia perfecta. El auto estaba impecable y el proceso fue muy sencillo.",
    rating: 5,
    image: "/placeholder.svg?height=200&width=200",
  },
]

// Horarios de atención
export const BUSINESS_HOURS = {
  weekdays: "Lunes a Viernes: 9:00 - 19:00",
  saturday: "Sábados: 10:00 - 14:00",
  sunday: "Domingos: Cerrado",
}
